apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi
  labels:
    name: python-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      name: python-fastapi
  template:
    metadata:
      name: python-fastapi
      labels:
        name: python-fastapi
    spec:
      containers:
        - name: python-fastapi-onnx-runtime
          image: 423062414102.dkr.ecr.ap-northeast-2.amazonaws.com/python-fastapi:0.1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
